import test from 'node:test';
import assert from 'node:assert/strict';
import {DEFAULT_RULE,ruleSchema,type Rule,EXAMPLES} from '../lib/radar/domain.ts';
import {demoSnapshot,evaluate,fingerprint,nextDelay} from '../lib/radar/engine.ts';
import {fallbackCompile,compile,boundary} from '../lib/radar/compiler.ts';
const now=Date.UTC(2026,9,7,2,30);const r=structuredClone(DEFAULT_RULE);const context={now,lastAlert:null,previousStatus:'ready'};
test('明确价格阈值被正确解析，默认值可检查',()=>{const x=fallbackCompile(EXAMPLES[0].text);assert.equal(x.mode,'template');assert.deepEqual(x.rule?.conditions,[{kind:'price',op:'lt',value:1600}]);assert.equal(x.rule?.cooldownMin,30)});
test('跌幅转换为负的日内涨跌幅，组合关系为且',()=>{const x=fallbackCompile(EXAMPLES[3].text);assert.equal(x.rule?.logic,'all');assert.deepEqual(x.rule?.conditions,[{kind:'change',op:'lt',value:-2},{kind:'heat',op:'gt',value:80}])});
test('事件关键词不丢失',()=>assert.deepEqual(fallbackCompile(EXAMPLES[1].text).rule?.conditions,[{kind:'event',keyword:'回购'}]));
test('日历提前天数被正确解析',()=>assert.deepEqual(fallbackCompile(EXAMPLES[2].text).rule?.conditions,[{kind:'calendar',daysBefore:3}]));
test('模糊阈值需要澄清',()=>assert.equal(fallbackCompile('贵州茅台大跌时提醒我').rule,null));
test('不支持的指标不能静默丢弃',()=>assert.equal(fallbackCompile('贵州茅台低于1600元且成交量放大时提醒我').rule,null));
test('多个标的需要拆分',()=>assert.equal(fallbackCompile('贵州茅台和宁德时代低于100元').rule,null));
test('交易时段不能默认为全天',()=>assert.equal(fallbackCompile('贵州茅台低于1600元，交易时段每5分钟检查').rule,null));
test('越权交易和收益承诺被拦截',()=>{assert.ok(boundary('自动买入贵州茅台'));assert.ok(boundary('保证收益'));assert.equal(fallbackCompile('帮我买入贵州茅台').refused,true)});
test('非法数值、无穷、额外字段及无效标的被拒绝',()=>{for(const value of [NaN,Infinity,-1,0])assert.equal(ruleSchema.safeParse({...r,conditions:[{kind:'price',op:'lt',value}]}).success,false);assert.equal(ruleSchema.safeParse({...r,executeTrade:true}).success,false);assert.equal(ruleSchema.safeParse({...r,symbol:'FAKE'}).success,false)});
test('检查间隔下限和热度边界被校验',()=>{assert.equal(ruleSchema.safeParse({...r,intervalMin:1}).success,false);assert.equal(ruleSchema.safeParse({...r,conditions:[{kind:'heat',op:'gt',value:101}]}).success,false)});
test('正常样本未命中，解释含实际值',async()=>{const x=await evaluate(r,demoSnapshot(r,now),context);assert.equal(x.status,'not_matched');assert.match(x.reason,/1688.8/)});
test('条件命中生成提醒决定',async()=>{const x=await evaluate(r,demoSnapshot(r,now,'match'),context);assert.equal(x.status,'matched');assert.ok(x.fingerprint);assert.equal(x.evidence[0].passed,true)});
test('严格小于不包含边界值',async()=>{const d=demoSnapshot(r,now);d.price=1600;assert.equal((await evaluate(r,d,context)).status,'not_matched')});
test('不高于包含边界值',async()=>{const rule:Rule={...r,conditions:[{kind:'price',op:'lte',value:1600}]};const d=demoSnapshot(rule,now);d.price=1600;assert.equal((await evaluate(rule,d,context)).status,'matched')});
for(const scenario of ['stale','conflict','failure'] as const)test(`${scenario} 必须无法判断，不能误报或归为未命中`,async()=>{const x=await evaluate(r,demoSnapshot(r,now,scenario),context);assert.equal(x.status,'unknown');assert.equal(x.fingerprint,null);assert.equal(x.evidence[0].passed,null)});
test('未来时间戳被拒绝',async()=>{const d=demoSnapshot(r,now);d.observedAt=now+120000;assert.equal((await evaluate(r,d,context)).status,'unknown')});
test('数据标的必须与规则一致',async()=>{const d=demoSnapshot(r,now);d.symbol='000300.SH';assert.equal((await evaluate(r,d,context)).status,'unknown')});
test('缺失数值不能当零使用',async()=>{const d=demoSnapshot(r,now);d.price=NaN;assert.equal((await evaluate(r,d,context)).status,'unknown')});
test('同证据优先去重，即使仍在冷却期',async()=>{const x=await evaluate(r,demoSnapshot(r,now,'match'),{...context,seen:true,lastAlert:now-100});assert.equal(x.status,'duplicate')});
test('新证据在冷却期内不提醒',async()=>{const x=await evaluate(r,demoSnapshot(r,now,'match'),{...context,lastAlert:now-60000});assert.equal(x.status,'cooldown')});
test('冷却到期允许新证据提醒',async()=>{assert.equal((await evaluate(r,demoSnapshot(r,now,'match'),{...context,lastAlert:now-30*60000})).status,'matched')});
test('故障恢复后明确标记重新判断',async()=>{const x=await evaluate(r,demoSnapshot(r,now),{...context,previousStatus:'unknown'});assert.equal(x.recovered,true);assert.equal(x.status,'not_matched')});
test('持续故障不能宣称恢复',async()=>assert.equal((await evaluate(r,demoSnapshot(r,now,'failure'),{...context,previousStatus:'unknown'})).recovered,false));
test('且与或的结果不同',async()=>{const rule:Rule={...r,conditions:[{kind:'price',op:'lt',value:100},{kind:'heat',op:'gt',value:10}]};const d=demoSnapshot(rule,now);assert.equal((await evaluate(rule,d,context)).status,'not_matched');assert.equal((await evaluate({...rule,logic:'any'},d,context)).status,'matched')});
test('保守组合策略：即使或的另一项满足，数据缺失仍为未知',async()=>{const rule:Rule={...r,logic:'any',conditions:[{kind:'price',op:'lt',value:100},{kind:'heat',op:'gt',value:10}]};const d=demoSnapshot(rule,now);d.price=NaN;assert.equal((await evaluate(rule,d,context)).status,'unknown')});
test('公告去重使用事件 ID，不随采集快照时间改变',async()=>{const rule:Rule={...r,conditions:[{kind:'event',keyword:'回购'}]};assert.equal(await fingerprint(rule,demoSnapshot(rule,now)),await fingerprint(rule,demoSnapshot(rule,now+300000)))});
test('日历已过去不能继续提醒',async()=>{const rule:Rule={...r,conditions:[{kind:'calendar',daysBefore:3}]};const d=demoSnapshot(rule,now);d.calendar.at=now-86400000;assert.equal((await evaluate(rule,d,context)).status,'not_matched')});
test('退避重试有上限',()=>{assert.equal(nextDelay(r,'unknown',0),60000);assert.equal(nextDelay(r,'unknown',2),240000);assert.equal(nextDelay(r,'unknown',99),3600000)});
test('没有密钥不能伪称使用 DeepSeek',async()=>assert.equal((await compile(EXAMPLES[0].text,{})).mode,'template'));
test('API 失败降级并解释状态码',async()=>{const x=await compile(EXAMPLES[0].text,{key:'test-only',fetcher:async()=>new Response('{}',{status:429})});assert.equal(x.mode,'template');assert.equal(x.upstreamStatus,429)});
test('JSON 有效但规则非法也必须拒绝模型结果',async()=>{const x=await compile(EXAMPLES[0].text,{key:'test-only',fetcher:async()=>Response.json({choices:[{message:{content:JSON.stringify({rule:{...r,conditions:[{kind:'price',op:'lt',value:-99}]},questions:[],warnings:[],refused:false})}}]})});assert.equal(x.mode,'template');assert.match(x.warnings[0],/校验/)});
test('合法模型结果有模型名和提示词版本',async()=>{const x=await compile(EXAMPLES[0].text,{key:'test-only',fetcher:async()=>Response.json({choices:[{message:{content:JSON.stringify({rule:r,questions:[],warnings:[],refused:false})}}],usage:{total_tokens:123}})});assert.equal(x.mode,'deepseek');assert.equal(x.promptVersion,'rule-compiler-v1.0');assert.equal(x.rule?.symbol,r.symbol)});
