import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const owners=sqliteTable('owners',{id:text('id').primaryKey(),createdAt:integer('created_at').notNull()});
export const tasks=sqliteTable('tasks',{id:text('id').primaryKey(),owner:text('owner').notNull(),rule:text('rule').notNull(),version:integer('version').notNull().default(1),enabled:integer('enabled').notNull().default(1),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),expiresAt:integer('expires_at').notNull(),nextRun:integer('next_run').notNull(),lastRun:integer('last_run'),lastAlert:integer('last_alert'),status:text('status').notNull().default('ready'),reason:text('reason').notNull().default('等待首次检查'),failures:integer('failures').notNull().default(0),scenario:text('scenario').notNull().default('normal'),leaseUntil:integer('lease_until').notNull().default(0),lastData:text('last_data')},t=>[index('idx_tasks_owner').on(t.owner),index('idx_tasks_due').on(t.enabled,t.nextRun)]);
export const versions=sqliteTable('versions',{id:text('id').primaryKey(),taskId:text('task_id').notNull(),version:integer('version').notNull(),rule:text('rule').notNull(),note:text('note').notNull(),at:integer('at').notNull()},t=>[uniqueIndex('idx_versions_task_version').on(t.taskId,t.version)]);
export const runs=sqliteTable('runs',{id:text('id').primaryKey(),taskId:text('task_id').notNull(),owner:text('owner').notNull(),version:integer('version').notNull(),at:integer('at').notNull(),trigger:text('trigger').notNull(),decision:text('decision').notNull()},t=>[index('idx_runs_task_time').on(t.taskId,t.at)]);
export const alerts=sqliteTable('alerts',{id:text('id').primaryKey(),taskId:text('task_id').notNull(),owner:text('owner').notNull(),version:integer('version').notNull(),runId:text('run_id').notNull(),fingerprint:text('fingerprint').notNull(),at:integer('at').notNull(),title:text('title').notNull(),reason:text('reason').notNull(),readAt:integer('read_at')},t=>[uniqueIndex('idx_alerts_dedupe').on(t.taskId,t.version,t.fingerprint),index('idx_alerts_owner').on(t.owner,t.at)]);
export const meta=sqliteTable('meta',{key:text('key').primaryKey(),value:text('value').notNull()});
export const aiUsage=sqliteTable('ai_usage',{key:text('key').primaryKey(),count:integer('count').notNull().default(0)});
export const aiRecords=sqliteTable('ai_records',{id:text('id').primaryKey(),owner:text('owner').notNull(),at:integer('at').notNull(),input:text('input').notNull(),result:text('result').notNull()},t=>[index('idx_ai_owner').on(t.owner,t.at)]);
