import {env} from 'cloudflare:workers';
import {ruleSchema,SEED_RULES,CATALOG,SCENARIOS,type Task,type Rule,type Scenario} from './domain';
import {demoSnapshot,evaluate,fingerprint,nextDelay} from './engine';
import {compile,PROMPT_VERSION} from './compiler';
type Row=Record<string,unknown>;
const uid=()=>crypto.randomUUID();const DAYS7=7*86400000;
export const db=()=>{if(!env.DB)throw new Error('数据库暂时不可用，请稍后重试。');return env.DB;};
function taskRow(r:Row):Task{return {id:String(r.id),owner:String(r.owner),rule:JSON.parse(String(r.rule)),version:Number(r.version),enabled:!!r.enabled,createdAt:Number(r.created_at),updatedAt:Number(r.updated_at),expiresAt:Number(r.expires_at),nextRun:Number(r.next_run),lastRun:r.last_run===null?null:Number(r.last_run),lastAlert:r.last_alert===null?null:Number(r.last_alert),status:String(r.status),reason:String(r.reason),failures:Number(r.failures),scenario:r.scenario as Scenario,...(r.last_data?{lastData:JSON.parse(String(r.last_data))}:{})};}
export class AppError extends Error{constructor(message:string,public code=400){super(message);}}
export async function seed(owner:string){const exists=await db().prepare('SELECT id FROM owners WHERE id=?').bind(owner).first();if(exists)return;const now=Date.now();const statements=[db().prepare('INSERT INTO owners (id,created_at) VALUES (?,?)').bind(owner,now)];for(const rule of SEED_RULES){const id=uid();statements.push(insertTask(id,owner,rule,now));statements.push(insertVersion(id,1,rule,'初始化演示规则，等待检查',now));}try{await db().batch(statements);}catch(error){if(!await db().prepare('SELECT id FROM owners WHERE id=?').bind(owner).first())throw error;}}
function insertTask(id:string,owner:string,rule:Rule,now:number){return db().prepare('INSERT INTO tasks (id,owner,rule,created_at,updated_at,expires_at,next_run) VALUES (?,?,?,?,?,?,?)').bind(id,owner,JSON.stringify(rule),now,now,now+DAYS7,now);}
function insertVersion(id:string,v:number,rule:Rule,note:string,now:number){return db().prepare('INSERT INTO versions (id,task_id,version,rule,note,at) VALUES (?,?,?,?,?,?)').bind(uid(),id,v,JSON.stringify(rule),note,now);}
export async function owned(id:string,owner:string){const r=await db().prepare('SELECT * FROM tasks WHERE id=? AND owner=?').bind(id,owner).first<Row>();if(!r)throw new AppError('任务不存在或不属于当前空间。',404);return taskRow(r);}
export async function state(owner:string){
 const [t,a,count,heart,ai]=await Promise.all([db().prepare('SELECT * FROM tasks WHERE owner=? ORDER BY created_at DESC').bind(owner).all<Row>(),db().prepare('SELECT * FROM alerts WHERE owner=? ORDER BY at DESC LIMIT 100').bind(owner).all(),db().prepare('SELECT (SELECT count(*) FROM runs WHERE owner=?) AS checks,(SELECT count(*) FROM alerts WHERE owner=? AND read_at IS NULL) AS unread,(SELECT count(*) FROM alerts WHERE owner=?) AS alerts').bind(owner,owner,owner).first(),db().prepare("SELECT value FROM meta WHERE key='scheduler'").first<{value:string}>(),db().prepare('SELECT id,at,result FROM ai_records WHERE owner=? ORDER BY at DESC LIMIT 10').bind(owner).all<Row>()]);
 return {tasks:t.results.map(taskRow),alerts:a.results,counts:count,serverNow:Date.now(),catalog:CATALOG,scheduler:heart?JSON.parse(heart.value):null,model:{configured:!!(env as unknown as Record<string,string>).DEEPSEEK_API_KEY,name:(env as unknown as Record<string,string>).DEEPSEEK_MODEL||'deepseek-flash',promptVersion:PROMPT_VERSION},aiRecords:ai.results.map(r=>({...r,result:JSON.parse(String(r.result))})),dataMode:'demo',dataSource:'知更合成样本 v1'};
}
export async function create(owner:string,input:unknown){const rule=ruleSchema.parse(input);const count=await db().prepare('SELECT count(*) AS n FROM tasks WHERE owner=?').bind(owner).first<{n:number}>();if((count?.n??0)>=20)throw new AppError('演示空间最多保留 20 个任务。',429);const now=Date.now(),id=uid();await db().batch([insertTask(id,owner,rule,now),insertVersion(id,1,rule,'确认规则并创建任务',now)]);await runTask(id,owner,'manual');return owned(id,owner);}
export async function update(owner:string,id:string,input:{rule?:unknown;version?:number;enabled?:boolean;scenario?:Scenario}){
 const task=await owned(id,owner);const now=Date.now();if(input.version!==task.version)throw new AppError('规则已在其他窗口修改，请刷新后重试。',409);
 if(input.rule){const rule=ruleSchema.parse(input.rule);const result=await db().batch([db().prepare('UPDATE tasks SET rule=?,version=version+1,updated_at=?,next_run=?,status=?,reason=?,last_alert=NULL,failures=0 WHERE id=? AND owner=? AND version=? AND lease_until<=? RETURNING id').bind(JSON.stringify(rule),now,now,task.enabled?'ready':'paused','规则已更新，下一次检查使用新版本；历史记录保留。',id,owner,task.version,now),db().prepare('INSERT INTO versions (id,task_id,version,rule,note,at) SELECT ?,?,?,?,?,? WHERE changes()=1').bind(uid(),id,task.version+1,JSON.stringify(rule),'用户编辑并确认规则；旧版证据与提醒保留',now)]);if(!result[0].meta.changes)throw new AppError('任务正在检查或已修改，请稍后重试。',409);}
 else if(typeof input.enabled==='boolean'){const changed=await db().prepare('UPDATE tasks SET enabled=?,updated_at=?,expires_at=?,next_run=?,status=?,reason=? WHERE id=? AND owner=? AND version=? AND lease_until<=? RETURNING id').bind(input.enabled?1:0,now,input.enabled?now+DAYS7:task.expiresAt,now,input.enabled?'ready':'paused',input.enabled?'已恢复监控，等待下一次检查。':'用户已暂停。暂停期间不检查、不补发。',id,owner,task.version,now).first();if(!changed)throw new AppError('任务正在检查，请稍后重试。',409);}
 else if(input.scenario&&input.scenario in SCENARIOS){const changed=await db().prepare('UPDATE tasks SET scenario=?,updated_at=?,next_run=? WHERE id=? AND owner=? AND version=? AND lease_until<=? RETURNING id').bind(input.scenario,now,now,id,owner,task.version,now).first();if(!changed)throw new AppError('任务正在检查，请稍后重试。',409);}
 else throw new AppError('没有有效的修改项。');return owned(id,owner);
}
export async function runTask(id:string,owner:string,trigger:'manual'|'scheduled'){
 const now=Date.now();const row=await db().prepare('UPDATE tasks SET lease_until=? WHERE id=? AND owner=? AND enabled=1 AND expires_at>? AND lease_until<=? RETURNING *').bind(now+60000,id,owner,now,now).first<Row>();
 if(!row)throw new AppError('任务已暂停、到期或正在检查，请稍后重试。',409);
 const task=taskRow(row);try{
 const data=demoSnapshot(task.rule,now,task.scenario);const fp=await fingerprint(task.rule,data);const seen=await db().prepare('SELECT id FROM alerts WHERE task_id=? AND version=? AND fingerprint=?').bind(id,task.version,fp).first();
 const decision=await evaluate(task.rule,data,{now,lastAlert:task.lastAlert,previousStatus:task.status,seen:!!seen});const runId=uid();const failures=decision.status==='unknown'?task.failures+1:0;
 const statements=[db().prepare('INSERT INTO runs (id,task_id,owner,version,at,trigger,decision) VALUES (?,?,?,?,?,?,?)').bind(runId,id,owner,task.version,now,trigger,JSON.stringify(decision)),db().prepare('UPDATE tasks SET status=?,reason=?,last_run=?,next_run=?,last_alert=?,failures=?,lease_until=0,last_data=? WHERE id=? AND version=?').bind(decision.status,decision.reason,now,now+nextDelay(task.rule,decision.status,task.failures),decision.status==='matched'?now:task.lastAlert,failures,JSON.stringify(data),id,task.version)];
 if(decision.status==='matched')statements.push(db().prepare('INSERT INTO alerts (id,task_id,owner,version,run_id,fingerprint,at,title,reason) VALUES (?,?,?,?,?,?,?,?,?)').bind(uid(),id,owner,task.version,runId,fp,now,task.rule.title,decision.reason));
 await db().batch(statements);return {id:runId,at:now,version:task.version,trigger,decision};
 }catch(e){await db().prepare('UPDATE tasks SET lease_until=0 WHERE id=? AND lease_until=?').bind(id,now+60000).run();throw e;}
}
export async function detail(owner:string,id:string){const task=await owned(id,owner);const [runs,versions]=await Promise.all([db().prepare('SELECT * FROM runs WHERE task_id=? AND owner=? ORDER BY at DESC LIMIT 60').bind(id,owner).all<Row>(),db().prepare('SELECT * FROM versions WHERE task_id=? ORDER BY version DESC').bind(id).all<Row>()]);return {task,runs:runs.results.map(x=>({...x,decision:JSON.parse(String(x.decision))})),versions:versions.results.map(x=>({...x,rule:JSON.parse(String(x.rule))}))};}
export async function cron(){const now=Date.now();await db().prepare("UPDATE tasks SET enabled=0,status='expired',reason='演示监控期限已结束，可手动恢复并延长 7 天。' WHERE enabled=1 AND expires_at<=?").bind(now).run();const tasks=await db().prepare('SELECT id,owner FROM tasks WHERE enabled=1 AND expires_at>? AND next_run<=? AND lease_until<=? ORDER BY next_run LIMIT 50').bind(now,now,now).all<{id:string;owner:string}>();let checked=0,failed=0;for(const t of tasks.results)try{await runTask(t.id,t.owner,'scheduled');checked++;}catch{failed++;}const value={lastTick:now,checked,failed,requestedCadenceMin:5,driver:'外部定时调用；实际执行时间可能延迟'};await db().prepare("INSERT INTO meta (key,value) VALUES ('scheduler',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(JSON.stringify(value)).run();return value;}
export async function generate(owner:string,text:string){if(typeof text!=='string'||!text.trim()||text.length>1000)throw new AppError('请输入 1–1000 字的监控关注点。');const day=new Date().toISOString().slice(0,10);for(const [key,max] of [[`global:${day}`,200],[`${owner}:${day}`,30]] as const){const result=await db().prepare('INSERT INTO ai_usage (key,count) VALUES (?,1) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key).first<{count:number}>();if((result?.count??0)>max)throw new AppError('今日生成次数达到演示上限，请使用手动配置。',429);}
 const config=env as unknown as Record<string,string>;const result=await compile(text,{key:config.DEEPSEEK_API_KEY,model:config.DEEPSEEK_MODEL});await db().prepare('INSERT INTO ai_records (id,owner,at,input,result) VALUES (?,?,?,?,?)').bind(uid(),owner,Date.now(),text,JSON.stringify(result)).run();return result;
}
export async function markRead(owner:string,id:string){await db().prepare('UPDATE alerts SET read_at=? WHERE id=? AND owner=?').bind(Date.now(),id,owner).run();return {ok:true};}
